name: CI

on:
  workflow_dispatch:
  push:
  pull_request:
    types: [ reopened, opened, synchronize ]

permissions:
  contents: read

jobs:

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-14, windows-latest ]
        java: [ 17, 21 ]
      fail-fast: false
      max-parallel: 4
    name: Test JDK ${{ matrix.java }}, ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - name: Set up JDK
        uses: actions/setup-java@v5.6.0
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'
      - name: Test with Maven
        run: mvn -B clean test

  test-coverage:
    runs-on: ubuntu-latest
    name: Run tests and upload coverage
    steps:
      - uses: actions/checkout@v7
      - name: Set up JDK
        uses: actions/setup-java@v5.6.0
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'
      - name: Test with Maven
        run: mvn -B clean test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: the-thing/zam
